### ISSUE TITLE
Test Day TODOs

### ISSUE THREAD

**Issue by younesr1** [nightingale-project/nightingale#41]
This is a list of things that need to be fixed after test day. These are non-blocking issues or permanent replacements to temporary fixes:

1. add ben's new repo to the rosinstall
2. Add automated our own automated homing sequence

**Comment by bdschnapp** [comment]
remove class type print statements from UI

**Comment by bdschnapp** [comment]
add felix's repos to rosinstall

**Comment by bdschnapp** [comment]
noticed issue realted to a packet header with size over 1GB. unsure if this is a consistent error or not

**Comment by bdschnapp** [comment]
Grippers seem to not open and close when commanded

**Comment by bdschnapp** [comment]
on screen where patient consents to arm delivering items, change the screen to show that the arm is in progress of planning the path once the patient clicks the button. (currently after hitting the start button, nothing happens for about 5 seconds.)

**Comment by FelixKHWong** [comment]
I'm not able to find the print statements for the ros bridge on main in the nightingale_ros_bridge folder. Maybe it was a change only done on the MOVO computers? For the screen to change during arm planning I can add a popup in V1 to show that the process is starting and the arm is planning. EDIT: Just checked my PR for tablet V1 and I've already created the popup to say the arm is planning

**Comment by FelixKHWong** [comment]
Check and fix status conditions during each phase for mission planner

**Comment by FelixKHWong** [comment]
Get better poses in the map for handoff
